### ISSUE TITLE
Field layout

### ISSUE THREAD

**Issue by technocrat** [arifyali/mail-in-ballot-dropoff#2]
I suggest a revision to

`locality,name,address,city,zip,st,remarks`

To provide a zip lookup. Remarks can be used for information such as hours and directions (e.g., "in back of police station and latest time to drop off.")

If you agree, I can redo PA and send a pull request

**Comment by arifyali** [comment]
I like it. Please modify PA, edit the readme with the new schema, and send a pull request.
