### ISSUE TITLE
adding other state locations

### ISSUE THREAD

**Issue by caretak3r** [arifyali/mail-in-ballot-dropoff#6]
this is a bit tough, since each state/county might have different information/updated irregularly, but would something like this be a starting point for states (example, NJ):

https://nj.gov/state/elections/assets/pdf/election-results/2020/2020-drop-box-locations.pdf

i'll see what I can do looking for the other states, how much progress have you made there?

**Comment by arifyali** [comment]
New Jersey is an interesting case because they recently rolled out a massive mail in ballot initiative. something like that would be useful but in a CSV format.￼

**Comment by arifyali** [comment]
In terms of other states. I've got Pennsylvania and Iowa with leads on Minnesota and Washington. Honestly, this is not bad for something I literally started yesterday.￼￼

**Comment by caretak3r** [comment]
@arifyali at the very least we know the fields required for basic usage. does it then make sense to gather the 50~ states datasets, even if in different formats? we could easily convert pdfs/scraping into csvs for now, then look at a db.

**Comment by arifyali** [comment]
Let's just get them into CSV's for now. I'm not thinking about the use of a database yet. There's no use of a database until there's actual data￼
